{
 "title": "Energy usage",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Meter Readings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Electricity (KWh)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "electricity_meter_reading" }
   ]
  },
  {
   "title": "Gas (m³)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gas_meter_reading" }
   ]
  },
  {
   "title": "Gas (KWh)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(gas_meter_reading) * 10.96497333"
    }
   ]
  },
  { "title": "Electricity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Load (Selected Period)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "electricity_draw",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Now",
     "measurement": "electricity",
     "query": "SELECT sum(\"consumption\") FROM \"electricity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    { "expr": "range_avg(electricity_draw)", "legendFormat": "Average" },
    { "expr": "range_min(electricity_draw)", "legendFormat": "Min" },
    { "expr": "range_max(electricity_draw)", "legendFormat": "Max" }
   ]
  },
  {
   "title": "Usage (Energy)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "range_avg(electricity_draw) * $__range_s / 3600",
     "legendFormat": "Selected"
    },
    {
     "expr": "electricity_consumption_daily",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Today",
     "measurement": "electricity",
     "query": "SELECT sum(\"cost\")/100 FROM \"electricity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    { "expr": "electricity_consumption_weekly", "legendFormat": "This week" },
    {
     "expr": "electricity_consumption_monthly",
     "legendFormat": "This month"
    }
   ]
  },
  {
   "title": "Usage (Cost)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(range_avg(electricity_draw) * $__range_s / 3600) * electricity_unit_rate",
     "legendFormat": "Selected"
    },
    {
     "expr": "electricity_consumption_daily * electricity_unit_rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Today",
     "measurement": "electricity",
     "query": "SELECT sum(\"total_cost\")/100 FROM \"electricity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "expr": "electricity_consumption_weekly * electricity_unit_rate",
     "legendFormat": "This week"
    },
    {
     "expr": "electricity_consumption_monthly * electricity_unit_rate",
     "legendFormat": "This month"
    }
   ]
  },
  {
   "title": "Total Cost",
   "type": "stat",
   "description": "Including standing charges",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(range_avg(electricity_draw) * $__range_s / 3600) * electricity_unit_rate + (electricity_standing_charge * $__range_s / 86400)",
     "legendFormat": "Selected"
    },
    {
     "expr": "electricity_consumption_daily * electricity_unit_rate + electricity_standing_charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Today",
     "measurement": "electricity",
     "query": "SELECT sum(\"total_cost\")/100 FROM \"electricity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "expr": "electricity_consumption_weekly * electricity_unit_rate + (7*electricity_standing_charge)",
     "legendFormat": "This week"
    },
    {
     "expr": "electricity_consumption_monthly * electricity_unit_rate + (30*electricity_standing_charge)",
     "legendFormat": "This month"
    }
   ]
  },
  {
   "title": "Electricity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "kwatt", "label": "Usage" }
   ],
   "targets": [
    {
     "alias": "Usage",
     "expr": "electricity_draw",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "Usage",
     "measurement": "electricity",
     "query": "SELECT mean(\"consumption\") FROM \"electricity\" WHERE $timeFilter GROUP BY time(30m) fill(linear)",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Go cost",
     "expr": "electricity_draw * electricity_unit_rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "Cost",
     "measurement": "electricity",
     "query": "SELECT mean(\"cost\")/100 FROM \"electricity\" WHERE $timeFilter GROUP BY time(30m) fill(linear)",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Gas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Usage (Energy)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(range_max(gas_meter_reading) - range_min(gas_meter_reading)) * 10.96497333",
     "legendFormat": "Selected"
    },
    {
     "expr": "gas_consumption_daily",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Today",
     "measurement": "gas",
     "query": "SELECT sum(\"consumption\") FROM \"gas\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    { "expr": "gas_consumption_weekly", "legendFormat": "This Week" },
    { "expr": "gas_consumption_monthly", "legendFormat": "This Month" }
   ]
  },
  {
   "title": "Used (Cost)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(range_max(gas_draw) - range_min(gas_draw)) * gas_unit_rate",
     "legendFormat": "Selected"
    },
    {
     "expr": "(gas_consumption_daily) * gas_unit_rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Today",
     "measurement": "gas",
     "query": "SELECT sum(\"consumption\") FROM \"gas\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "expr": "(gas_consumption_weekly) * gas_unit_rate",
     "legendFormat": "This week"
    },
    {
     "expr": "(gas_consumption_monthly) * gas_unit_rate",
     "legendFormat": "This month"
    }
   ]
  },
  {
   "title": "Total Cost",
   "type": "stat",
   "description": "Including standing charges",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(range_max(gas_draw) - range_min(gas_draw)) * gas_unit_rate + (gas_standing_charge * $__range_s / 86400)",
     "legendFormat": "Selected"
    },
    {
     "expr": "(gas_consumption_daily) * gas_unit_rate + gas_standing_charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Today",
     "measurement": "gas",
     "query": "SELECT sum(\"consumption\") FROM \"gas\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "expr": "(gas_consumption_weekly) * gas_unit_rate + (7*gas_standing_charge)",
     "legendFormat": "This week"
    },
    {
     "expr": "(gas_consumption_monthly) * gas_unit_rate + (30*gas_standing_charge)",
     "legendFormat": "This month"
    }
   ]
  },
  {
   "title": "Gas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "kwatth", "label": "Usage" }
   ],
   "targets": [
    {
     "alias": "Usage",
     "expr": "increase(gas_meter_reading_kwh)",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "Used",
     "measurement": "gas",
     "query": "SELECT mean(\"consumption\") FROM \"electricity\" WHERE $timeFilter GROUP BY time(30m) fill(linear)",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Cost",
     "expr": "increase(gas_meter_reading_kwh) * gas_unit_rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "Cost",
     "measurement": "electricity",
     "query": "SELECT mean(\"cost\")/100 FROM \"gas\" WHERE $timeFilter GROUP BY time(30m) fill(linear)",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}